longNames = ["Flick Left",
    "Flick Right",
    "Flick Up",
    "Flick Down",
    "Pan Left",
    "Pan Right",
    "Pan Up",
    "Pan Down",
    "Push",
    "Pull",
    "Double Tap",
    "Finger Wave Out",
    "Finger Wave In",
    "Whip",
    "Pluck",
    "Put",
    "Click",
    "Double Click",
    "Wobble",
    "Circle",
    "Erase"]

shortNames = ["flickl",
    "flcikr",
    "flicku",
    "flickd",
    "panl",
    "panr",
    "panu",
    "pand",
    "push",
    "pull",
    "dtap",
    "waveout",
    "wavein",
    "whip",
    "pluck",
    "put",
    "click",
    "dclick",
    "wobble",
    "circle",
    "erase"]